---

- import_tasks: config_cli.yml
  when: php5_cli_config | length

- import_tasks: config_fpm.yml
  when: php5_fpm_config | length

- import_tasks: config_apache2.yml
  when: php5_apache2_config | length

- name: Creating module config files
  file:
    path: "{{ php5_module_path }}/{{ item.name }}.ini"
    state: touch
  with_items: "{{ php5_modules }}"

- name: Fixing module config files
  lineinfile:
    dest: "{{ php5_module_path }}/{{ item.name }}.ini"
    insertbefore: BOF
    line: "[default]"
  with_items: "{{ php5_modules }}"

- name: Configuring modules
  ini_file:
    dest: "{{ php5_module_path }}/{{ item.0.name }}.ini"
    section: "{{ item.1.section | default(item.0.name) }}"
    option: "{{ item.1.section | default(item.0.name) }}.{{ item.1.option }}"
    value: "{{ item.1.value }}"
    state: present
  with_subelements:
    - "{{ php5_modules }}"
    - config

- name: Configuring logrotate
  template:
    src: etc-logrotate.d-php5.j2
    dest: /etc/logrotate.d/php5
    owner: "root"
    group: "root"
    mode: "0644"
