---

- name: Configuring fpm
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  notify: restart php5-fpm
  with_items: "{{ php5_fpm_config }}"

