---

- name: Installing packages
  apt: >
    pkg={{ item }}
    state=present
  with_items: php5_packages
  tags:
    - web
    - php5
    - install

- name: Creating log dir
  file: >
    dest=/var/log/php5
    state=directory
    owner=www-data
    group=adm
    mode=0750
  tags:
    - web
    - php5
    - install
