---

- name: Enabling modules
  command: >
    php5enmod {{ item.name }}
  args:
    creates: "/etc/php5/cli/conf.d/..-{{ item.name }}.ini"
  when: item.state is not defined or item.state != 'absent'
  with_items: "{{ php5_modules }}"

- name: Disabling modules
  command: >
    php5dismod {{ item.name }}
  args:
    removes: "/etc/php5/cli/conf.d/..-{{ item.name }}.ini"
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ php5_modules }}"

- name: Enabling pecl modules
  command: >
    php5enmod {{ item.name }}
  args:
    creates: "/etc/php5/cli/conf.d/..-{{ item.name }}.ini"
  when: item.state is not defined or item.state != 'absent'
  with_items: "{{ php5_pecl_packages }}"

- name: Disabling pecl modules
  command: >
    php5dismod {{ item.name }}
  args:
    removes: "/etc/php5/cli/conf.d/..-{{ item.name }}.ini"
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ php5_pecl_packages }}"
