---

# pear
- name: Updating pear channles
  command: pear update-channels
  tags:
    - web
    - php5
    - pear

- name: Upgrading pear packages
  command: printf "\n" | pear upgrade
  # this fails if there is some output for adding extension
  ignore_errors: yes
  tags:
    - web
    - php5
    - pear

- name: Setting auto discover
  command: pear config-set auto_discover 1
  tags:
    - web
    - php5
    - pear

- name: Installing pear packages
  command: printf "\n" | pear install {{ item }}
  with_items: php5_pear_packages
  register: pear_package_result
  changed_when: "'is already installed' not in pear_package_result.stdout"
  failed_when: "'No releases available for package' in pear_package_result.stdout"
  tags:
    - web
    - php5
    - pear
