---

# pear
- name: updating pear channles
  command: pear update-channels
  tags:
    - web
    - php5

- name: upgrading pear packages
  command: pear upgrade
  tags:
    - web
    - php5

- name: setting auto discover
  command: pear config-set auto_discover 1
  tags:
    - web
    - php5

- name: installing pear packages
  command: pear install {{ item }}
  with_items: php5_pear_packages
  # this fails if the same package is already installed...
  ignore_errors: yes
  tags:
    - web
    - php5
