---

- name: Updating pear channles
  command: pear update-channels

- name: Upgrading pear packages
  # this fails if there is some output for adding extension
  shell: >
    echo "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | pear upgrade
  ignore_errors: yes

- name: Setting auto discover
  command: pear config-set auto_discover 1

- name: Installing pear packages
  shell: >
    echo "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | pear install {{ item }}
  with_items: "{{ php5_pear_packages }}"
  register: pear_package_result
  changed_when: "'is already installed' not in pear_package_result.stdout"
  failed_when: "'No releases available for package' in pear_package_result.stdout"
