---

- name: Updating pecl channles
  command: pecl update-channels
  tags:
    - web
    - php5
    - pecl

- name: Upgrading pecl packages
  command: printf "\n" | pecl upgrade
  tags:
    - web
    - php5
    - pecl

- name: Installing pecl packages
  command: printf "\n" | pecl install {{ item.name }}
  with_items: php5_pecl_packages
  register: pecl_package_result
  changed_when: "'is already installed' not in pecl_package_result.stdout"
  failed_when: "'No releases available for package' in pecl_package_result.stdout"
  tags:
    - web
    - php5
    - pecl

- name: Adding module extension
  template: >
    src=etc-php5-mods-available-module.ini.j2
    dest=/etc/php5/mods-available/{{ item.name }}.ini
    owner=root
    group=root
    mode=0644
  with_items: php5_pecl_packages
  tags:
    - web
    - php5
    - pecl

- name: Configuring config
  ini_file: >
    dest=/etc/php5/mods-available/{{ item.0.name }}.ini
    section={{ item.1.section|default(item.0.name) }}
    option={{ item.1.section|default(item.0.name) }}.{{ item.1.option }}
    value={{ item.1.value }}
    state=present
  with_subelements:
    - php5_pecl_packages
    - config
  tags:
    - web
    - php5
    - pecl

- name: Enabling modules
  command: >
    php5enmod {{ item.name }}
    creates=/etc/php5/cli/conf.d/..-{{ item.name }}.ini
  when: item.state is not defined or item.state != 'absent'
  with_items: php5_pecl_packages
  tags:
    - web
    - php5
    - pecl

- name: Disabling modules
  command: >
    php5dismod {{ item.name }}
    removes=/etc/php5/cli/conf.d/..-{{ item.name }}.ini
  when: item.state is defined and item.state == 'absent'
  with_items: php5_pecl_packages
  tags:
    - web
    - php5
    - pecl
