---

# pecl
- name: updating pecl channles
  command: pecl update-channels
  tags:
    - web
    - php5

- name: upgrading pecl packages
  command: pecl upgrade
  tags:
    - web
    - php5

- name: installing pecl packages
  command: pecl install {{ item }}
  with_items: php5_pecl_packages
  # this fails if the same package is already installed (wtf)
  ignore_errors: yes
  tags:
    - web
    - php5
