---

- name: Updating pecl channles
  command: pecl update-channels

- name: Installing pecl packages
  shell: >
    echo "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | pecl install {{ item.name }}
  register: pecl_result
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: "{{ php5_pecl_packages }}"

- name: Adding pecl packages configs
  template:
    src: etc-php5-mods-available-module.ini.j2
    dest: "{{ php5_module_path }}/{{ item.name }}.ini"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ php5_pecl_packages }}"

- name: Configuring pecl packages configs
  ini_file:
    dest: "{{ php5_module_path }}/{{ item.0.name }}.ini"
    section: "{{ item.1.section | default(item.0.name) }}"
    option: "{{ item.1.section | default(item.0.name) }}.{{ item.1.option }}"
    value: "{{ item.1.value }}"
    state: present
  with_subelements:
    - "{{ php5_pecl_packages }}"
    - config

